// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for RevenueCatWebhookEventEventEnvironment.
const (
	PRODUCTION RevenueCatWebhookEventEventEnvironment = "PRODUCTION"
	SANDBOX    RevenueCatWebhookEventEventEnvironment = "SANDBOX"
)

// Defines values for RevenueCatWebhookEventEventPeriodType.
const (
	RevenueCatWebhookEventEventPeriodTypeINTRO       RevenueCatWebhookEventEventPeriodType = "INTRO"
	RevenueCatWebhookEventEventPeriodTypeNORMAL      RevenueCatWebhookEventEventPeriodType = "NORMAL"
	RevenueCatWebhookEventEventPeriodTypePREPAID     RevenueCatWebhookEventEventPeriodType = "PREPAID"
	RevenueCatWebhookEventEventPeriodTypePROMOTIONAL RevenueCatWebhookEventEventPeriodType = "PROMOTIONAL"
	RevenueCatWebhookEventEventPeriodTypeTRIAL       RevenueCatWebhookEventEventPeriodType = "TRIAL"
)

// Defines values for RevenueCatWebhookEventEventStore.
const (
	RevenueCatWebhookEventEventStoreAPPSTORE    RevenueCatWebhookEventEventStore = "APP_STORE"
	RevenueCatWebhookEventEventStorePLAYSTORE   RevenueCatWebhookEventEventStore = "PLAY_STORE"
	RevenueCatWebhookEventEventStorePROMOTIONAL RevenueCatWebhookEventEventStore = "PROMOTIONAL"
	RevenueCatWebhookEventEventStoreSTRIPE      RevenueCatWebhookEventEventStore = "STRIPE"
)

// Defines values for RevenueCatWebhookEventEventType.
const (
	BILLINGISSUE               RevenueCatWebhookEventEventType = "BILLING_ISSUE"
	CANCELLATION               RevenueCatWebhookEventEventType = "CANCELLATION"
	EXPERIMENTENROLLMENT       RevenueCatWebhookEventEventType = "EXPERIMENT_ENROLLMENT"
	EXPIRATION                 RevenueCatWebhookEventEventType = "EXPIRATION"
	INITIALPURCHASE            RevenueCatWebhookEventEventType = "INITIAL_PURCHASE"
	INVOICEISSUANCE            RevenueCatWebhookEventEventType = "INVOICE_ISSUANCE"
	NONRENEWINGPURCHASE        RevenueCatWebhookEventEventType = "NON_RENEWING_PURCHASE"
	PRODUCTCHANGE              RevenueCatWebhookEventEventType = "PRODUCT_CHANGE"
	RENEWAL                    RevenueCatWebhookEventEventType = "RENEWAL"
	SUBSCRIBERALIAS            RevenueCatWebhookEventEventType = "SUBSCRIBER_ALIAS"
	SUBSCRIPTIONEXTENDED       RevenueCatWebhookEventEventType = "SUBSCRIPTION_EXTENDED"
	SUBSCRIPTIONPAUSED         RevenueCatWebhookEventEventType = "SUBSCRIPTION_PAUSED"
	TEMPORARYENTITLEMENTGRANT  RevenueCatWebhookEventEventType = "TEMPORARY_ENTITLEMENT_GRANT"
	TEST                       RevenueCatWebhookEventEventType = "TEST"
	TRANSFER                   RevenueCatWebhookEventEventType = "TRANSFER"
	UNCANCELLATION             RevenueCatWebhookEventEventType = "UNCANCELLATION"
	VIRTUALCURRENCYTRANSACTION RevenueCatWebhookEventEventType = "VIRTUAL_CURRENCY_TRANSACTION"
)

// Defines values for WebhookResponseStatus.
const (
	Success WebhookResponseStatus = "success"
)

// ErrorResponse Error response structure
type ErrorResponse struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error type or code
	Error string `json:"error"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`
}

// RevenueCatWebhookEvent RevenueCat webhook event payload
type RevenueCatWebhookEvent struct {
	// Event Event details
	Event struct {
		// AppId Unique identifier of the app the event is associated with. Corresponds to an app within a project
		AppId string `json:"app_id"`

		// AppUserId Unique identifier for the user in your app
		AppUserId *string `json:"app_user_id,omitempty"`

		// CancelledAtMs Cancellation timestamp in milliseconds (for CANCELLATION events)
		CancelledAtMs *int64 `json:"cancelled_at_ms,omitempty"`

		// CountryCode Country code where the product was purchased
		CountryCode *string `json:"country_code,omitempty"`

		// Currency ISO 4217 currency code
		Currency *string `json:"currency,omitempty"`

		// Environment Environment where the event occurred
		Environment RevenueCatWebhookEventEventEnvironment `json:"environment"`

		// ExpirationAtMs Expiration timestamp in milliseconds
		ExpirationAtMs *int64 `json:"expiration_at_ms,omitempty"`

		// Id Unique identifier of the event
		Id string `json:"id"`

		// PeriodType Period type of the transaction
		PeriodType *RevenueCatWebhookEventEventPeriodType `json:"period_type,omitempty"`

		// Price Price in dollars
		Price *float32 `json:"price,omitempty"`

		// PriceInPurchasedCurrency Price in the currency used for purchase
		PriceInPurchasedCurrency *float32 `json:"price_in_purchased_currency,omitempty"`

		// ProductId Product/SKU identifier
		ProductId *string `json:"product_id,omitempty"`

		// PurchasedAtMs Purchase timestamp in milliseconds
		PurchasedAtMs *int64 `json:"purchased_at_ms,omitempty"`

		// RenewalNumber The number of renewals that this subscription has already gone through. Always starts at 1
		RenewalNumber *int `json:"renewal_number,omitempty"`

		// Store Store where the purchase was made
		Store RevenueCatWebhookEventEventStore `json:"store"`

		// Type Type of RevenueCat event
		Type RevenueCatWebhookEventEventType `json:"type"`
	} `json:"event"`
}

// RevenueCatWebhookEventEventEnvironment Environment where the event occurred
type RevenueCatWebhookEventEventEnvironment string

// RevenueCatWebhookEventEventPeriodType Period type of the transaction
type RevenueCatWebhookEventEventPeriodType string

// RevenueCatWebhookEventEventStore Store where the purchase was made
type RevenueCatWebhookEventEventStore string

// RevenueCatWebhookEventEventType Type of RevenueCat event
type RevenueCatWebhookEventEventType string

// WebhookResponse Successful webhook response
type WebhookResponse struct {
	// Message Human-readable message
	Message *string `json:"message,omitempty"`

	// Status Status of the webhook processing
	Status WebhookResponseStatus `json:"status"`
}

// WebhookResponseStatus Status of the webhook processing
type WebhookResponseStatus string

// HandleRevenueCatWebhookJSONRequestBody defines body for HandleRevenueCatWebhook for application/json ContentType.
type HandleRevenueCatWebhookJSONRequestBody = RevenueCatWebhookEvent
