// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for RevenueCatWebhookEventEventEnvironment.
const (
	PRODUCTION RevenueCatWebhookEventEventEnvironment = "PRODUCTION"
	SANDBOX    RevenueCatWebhookEventEventEnvironment = "SANDBOX"
)

// Defines values for RevenueCatWebhookEventEventStore.
const (
	AppStore    RevenueCatWebhookEventEventStore = "app_store"
	PlayStore   RevenueCatWebhookEventEventStore = "play_store"
	Promotional RevenueCatWebhookEventEventStore = "promotional"
	Stripe      RevenueCatWebhookEventEventStore = "stripe"
)

// Defines values for RevenueCatWebhookEventEventType.
const (
	BILLINGISSUE        RevenueCatWebhookEventEventType = "BILLING_ISSUE"
	CANCELLATION        RevenueCatWebhookEventEventType = "CANCELLATION"
	EXPIRATION          RevenueCatWebhookEventEventType = "EXPIRATION"
	INITIALPURCHASE     RevenueCatWebhookEventEventType = "INITIAL_PURCHASE"
	NONRENEWINGPURCHASE RevenueCatWebhookEventEventType = "NON_RENEWING_PURCHASE"
	PRODUCTCHANGE       RevenueCatWebhookEventEventType = "PRODUCT_CHANGE"
	RENEWAL             RevenueCatWebhookEventEventType = "RENEWAL"
	SUBSCRIPTIONPAUSED  RevenueCatWebhookEventEventType = "SUBSCRIPTION_PAUSED"
	TRANSFER            RevenueCatWebhookEventEventType = "TRANSFER"
	UNCANCELLATION      RevenueCatWebhookEventEventType = "UNCANCELLATION"
)

// Defines values for WebhookResponseStatus.
const (
	Success WebhookResponseStatus = "success"
)

// ErrorResponse Error response structure
type ErrorResponse struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error type or code
	Error string `json:"error"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`
}

// RevenueCatWebhookEvent RevenueCat webhook event payload
type RevenueCatWebhookEvent struct {
	// Event Event details
	Event struct {
		// AppUserId Unique identifier for the user in your app
		AppUserId string `json:"app_user_id"`

		// CancelledAtMs Cancellation timestamp in milliseconds (for CANCELLATION events)
		CancelledAtMs *int64 `json:"cancelled_at_ms,omitempty"`

		// Currency ISO 4217 currency code
		Currency *string `json:"currency,omitempty"`

		// Environment Environment where the event occurred
		Environment *RevenueCatWebhookEventEventEnvironment `json:"environment,omitempty"`

		// ExpirationAtMs Expiration timestamp in milliseconds
		ExpirationAtMs *int64 `json:"expiration_at_ms,omitempty"`

		// IsTrialPeriod Whether this is a trial period
		IsTrialPeriod *bool `json:"is_trial_period,omitempty"`

		// PriceInPurchasedCurrency Price in the currency used for purchase
		PriceInPurchasedCurrency *float32 `json:"price_in_purchased_currency,omitempty"`

		// ProductId Product/SKU identifier
		ProductId *string `json:"product_id,omitempty"`

		// PurchasedAtMs Purchase timestamp in milliseconds
		PurchasedAtMs *int64 `json:"purchased_at_ms,omitempty"`

		// Store Store where the purchase was made
		Store *RevenueCatWebhookEventEventStore `json:"store,omitempty"`

		// Type Type of RevenueCat event
		Type RevenueCatWebhookEventEventType `json:"type"`
	} `json:"event"`
}

// RevenueCatWebhookEventEventEnvironment Environment where the event occurred
type RevenueCatWebhookEventEventEnvironment string

// RevenueCatWebhookEventEventStore Store where the purchase was made
type RevenueCatWebhookEventEventStore string

// RevenueCatWebhookEventEventType Type of RevenueCat event
type RevenueCatWebhookEventEventType string

// WebhookResponse Successful webhook response
type WebhookResponse struct {
	// Message Human-readable message
	Message *string `json:"message,omitempty"`

	// Status Status of the webhook processing
	Status WebhookResponseStatus `json:"status"`
}

// WebhookResponseStatus Status of the webhook processing
type WebhookResponseStatus string

// HandleRevenueCatWebhookJSONRequestBody defines body for HandleRevenueCatWebhook for application/json ContentType.
type HandleRevenueCatWebhookJSONRequestBody = RevenueCatWebhookEvent
